services:
  bot:
    build:
      context: .
      no_cache: true   # Disable caching
    image: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}