name: CI/CD for Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh                # Create the .ssh directory
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Add the private key
        chmod 600 ~/.ssh/id_rsa        # Secure the key
        ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts  # Add server to known hosts



    - name: Build and Run Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no root@$87.106.165.63 << EOF
          cd /git_local/noah
          git pull
          docker compose down || true
          docker compose up -d --build
        EOF
