name: CI/CD for Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Build and Run Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_IP }} << EOF
          cd /git_local/noah
          git pull
          docker compose down || true
          docker compose up -d --build
        EOF
